services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    env_file: .env.prod
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    healthcheck:  # Adicionado para garantir que o MongoDB está pronto
      test: mongosh --eval "db.adminCommand('ping')"
      interval: 5s
      timeout: 30s
      retries: 3

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    env_file: .env.prod
    ports:
      - 5000:5000
    depends_on:
      mongodb:
        condition: service_healthy  # Só inicia após MongoDB estar pronto

volumes:
  mongo_data:
    driver: local